version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/circleci-spyfall-frontend
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout

      - run: sudo apt-get -y -qq install awscli

      - run: npm install

      - run: npm run build

      - run: aws s3 cp ./dist $S3_BUCKET --recursive